# Site settings
title: Metal Subs
email: byoigres@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
permalink: /blog/:year/:month/:day/:title/
url: "http://metalsub.github.io" # the base hostname & protocol for your site
is_dev: true
twitter_username: byoigres
github_username:  byoigres
social:
  Github:
    url: "http://github.com/byoigres"
    icon: "github"
  LinkedIn:
    url: "http://linkedid.com/in/byoigres"
    icon: "linkedin"
  Twitter:
    url: "http://twitter.com/byoigres"
    icon: "twitter"
exclude: [Gemfile, Gemfile.lock, Procfile, bower_components, CNAME]

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
